#!/usr/bin/env bash
# Transfer a file from a client to another
# Acceoting only four args


if [$# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATHE_TO_SSH_KEY"
else
  scp -o StrictHostkeyChecking=no -i "$4" "$1" "$3@$2":~
fi
