#!/usr/bin/env bash
# Install nginx on a web server listen to port 80
#serves a default page index.html on the HTTP GET req
#nginx on port 80

sudo apt-get update -y

sudo apt-get install nginx -y

sudo echo "Hello World!" > /var/www/html/index.html

sudo service nginx restart
