#!/usr/bin/env bash
# A bash scripts that install nginx on an ubuntu mach
# This scripts also configures the default webpage served to be "Hello World!"
#when req ur matches /redirect_me, it redirects to my channel
# when a page/file not found in the docs root is req the 404.html
# page is served to the client as stated with the error_page directive.

sudo apt-get update -y

sudo apt-get install nginx -y

echo "Hello World!" | sudo dd status=none of=/var/www/html/index.html

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

NEW_RULE="\\\n\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=dNsg4nKTTxk;\n\t}\n"

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default/bakup

sudo sed -i "53i $NEW_RULE" /etc/nginx/sites-available/default

NEW_RULE="\\\n\terror_page 404 /404.html;\n\n\tlocation = /404.html {\n\t\tinternal;\n\t}\n"

sudo sed -i "531 $NEW_RULE" /etc/nginx/sites-available/default

sudo service nginx reload 
