#!/usr/bin/env bash
# config an Nginx server to listen on port 80

rm /etc/nginx/sites-eenabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
