#!/usr/bin/env bash
# using while loop show "Best School" 10x
#  on the 9th iter, show "Hi" before "Best School"

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
