#!/usr/bin/env bash
# show numb from 1 - 20 in additions to:
# "bad luck from China" for the 4th iter
# "bad luck from japan" for the 9th iter
# "bad luck from italy" 17th loop


count=1

while [ $count -le 20 ]
do
  echo "$count"
  case $count in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( count++ ))
done
