#!/usr/bin/bash
#configured ufw for server 
sudo apt-get -y update
sudo apt-get install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo systemctl stop ufw
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
gudo ufw enable
sudo ufc status  verbose
